### ISSUE TITLE
decide on snake case vs camel case

### ISSUE THREAD

**Issue by ltalirz** [superstar54/weas-widget#42]
The current API mixes snake case and camel case
```
viewer.from_ase(atoms)
viewer.volumetricData = {"values": volume}
viewer.isoSettings = [{"isovalue": 0.0001, "mode": 0}]
```
[Pythonic would be snake case](https://peps.python.org/pep-0008/#descriptive-naming-styles)

**Comment by superstar54** [comment]
The reason they are mixed for the moment: the camel case is common in javascript, and is used in WEAS code. For the traits, e.g., `volumetricData`, there is also a counterpart in the WEAS code, facilitating straightforward synchronization without the need for a naming conversion map. For `from_ase`, it is only used in the Python code. 

> [Pythonic would be snake case](https://peps.python.org/pep-0008/#descriptive-naming-styles)

Yes, it's better not to mix different styles. I would also like to use the snake case. Later, I will try to make a name map to do this, like:
```
{"volumetric_data": "volumetricData"}
```
