### ISSUE TITLE
Tidy up top level namespace of `WeasWidget`?

### ISSUE THREAD

**Issue by ltalirz** [superstar54/weas-widget#43]
The top level namespace of `WeasWidget` is rather crowded (30+ attributes)

https://github.com/superstar54/weas-widget/blob/43d39f71088af5710186216ff40858ea368c8132/src/weas_widget/__init__.py#L15

Perhaps it would make sense to group some of those together and nest them.

Also, it appears there are some traitlets while other things are manipulated with `set_` methods, and to me as a new user it is not obvious why.

**Comment by superstar54** [comment]
Thanks, @ltalirz, for the great issues (suggestions) regarding improving the code. I will try to reply to some of them now, and others later when I have more ideas.

Indeed, there are too many attributes on the top level, and it better to group and nest them. But I need to look into the [any widget](https://anywidget.dev/en/getting-started/) and see if it supports traits in a nested namespace.

**Comment by manzt** [comment]
My recommendation would be to wrap the widget class and expose the `_repr_mimebundle_` (what displays the actual widget), and encapsulate the anywidget instance from end users. You can then proxy assignment to properties with with getter/setter patterns:

```py
class WeasWidget:

    def __init__(self):
        self._widget = WeasAnyWidget()

    @property
    def value(self):
        return self._widget.value

    @value.setter
    def value(self, update):
        return self._widget.value = update
   
    def _repr_mimebundle_(self, *args, **kwargs):
        return self._widget._repr_mimebundle_(*args, **kwargs)

```

**Comment by superstar54** [comment]
@manzt, thanks for the suggestion; it's very helpful! I made some adjustments to ensure compatibility with ipywidget 7.x.

```python
def _repr_mimebundle_(self, *args, **kwargs):
    # if ipywdigets > 8.0.0, use _repr_mimebundle_ instead of _ipython_display_
    if hasattr(self._widget, "_repr_mimebundle_"):
        return self._widget._repr_mimebundle_(*args, **kwargs)
    else:
        return self._widget._ipython_display_(*args, **kwargs)

```

**Comment by superstar54** [comment]
@manzt One issue I notice with the `_repr_mimebundle_` method is that I can not embed the widget into the `HBox` or `VBox` from `ipywidgets`.

Thus, I decide to wrapper the base widget by inheriting the `HBox`

```python
class Wrapper(HBox):

    def __init__(self, *args, **kwargs):
        self._widget = WeasWidget(*args, **kwargs)
        super().__init__(children=[self._widget])
    
    @property
    def value(self):
        return self._widget.value

    @value.setter
    def value(self, update):
        self._widget.value = update
```
