### ISSUE TITLE
Can I set change the color of the species?

### ISSUE THREAD

**Issue by hanjiahe1999** [superstar54/weas-widget#63]
I want to render the some molecular structures,and I learn the documentatioin. But the colors of CPK and Vesta are not so pretty good. So I want to set color by myself.
Did you have any suggestions?

**Comment by hanjiahe1999** [comment]
I try to use viewer.avr.color_by = "element"  / viewer.avr.color_by = "index" and viewer.avr.color_ramp, but it doesn't work.

**Comment by superstar54** [comment]
Hi @hanjiahe1999 , I have added this feature in the latest version. Please upgrade and try.
```bash
pip install weas-widget --upgrade
```
Please check the example in the [Custom color for each species](https://weas-widget.readthedocs.io/en/latest/color.html#custom-color-for-each-species) section.
