### ISSUE TITLE
No atoms is shown in the GUI.

### ISSUE THREAD

**Issue by hanjiahe1999** [superstar54/weas-widget#66]
It didn't show the particles.
the code is

```python
from ase.build import bulk
from ase.calculators.emt import EMT
import numpy as np
from weas_widget import WeasWidget

atoms = bulk('Au', cubic = True)
atoms *= [3, 3, 3]
atoms.positions += np.random.random((len(atoms), 3))
atoms.calc = EMT()
atoms.get_potential_energy()
# set the forces as an attribute
atoms.set_array("Force", atoms.calc.results["forces"])

viewer = WeasWidget()
viewer.from_ase(atoms)
viewer.avr.color_by = "Force"
viewer.avr.color_ramp = ["red", "yellow", "blue"]
viewer.avr.model_style = 1
viewer
```
But there are no bugs.  the jupyter show is this.
![img_v3_02fm_73aab0d4-2898-4ba7-924f-fc763bf1649g](https://github.com/user-attachments/assets/06a80c12-d627-454d-b7fe-f5cb418290c0)

**Comment by hanjiahe1999** [comment]
the weas-widget version is 0.1.7 and I also try to the 0.1.6. it doesn't work.

**Comment by superstar54** [comment]
Hi @hanjiahe1999 , I can not reproduce this issue.

Did you install `weas-widget` using `pip` or from the source of the repository?

**Comment by hanjiahe1999** [comment]
I used the pip

**Comment by superstar54** [comment]
I can not reproduce this in a fresh environment. Could you try it in a fresh environment?

Or could you share your environment here, .e.g., run
```
pip freeze > requirements.txt
```
If you are using conda:
```
conda env export > requirements.txt
```
and then share the `requirements.txt` file here.

**Comment by superstar54** [comment]
Hi @hanjiahe1999 , I assume this issue no longer exists in the latest version. Feel free to re-open this issue if you encounter it again.
